"""Initialize preview-kit in a repo."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import IO

from . import config


class InitError(Exception):
    """Initialization error."""


def symlink_preview_just(repo_root: Path, preview_kit_path: Path, force: bool = False) -> None:
    """Create symlink to preview.just in repo root."""
    link_path = repo_root / "preview.just"
    target = preview_kit_path / "preview.just"

    if link_path.exists() or link_path.is_symlink():
        if not force:
            raise InitError(f"preview.just already exists at {link_path}")
        link_path.unlink()

    if not target.exists():
        raise InitError(f"preview.just not found at {target}")

    link_path.symlink_to(target)


def write_config(repo_root: Path, cfg: config.PreviewKitConfig, force: bool = False) -> None:
    """Write preview-kit.toml to repo root."""
    config_path = repo_root / "preview-kit.toml"
    if config_path.exists() and not force:
        raise InitError(f"preview-kit.toml already exists at {config_path}")

    lines = [
        "# preview-kit.toml — per-repo configuration.",
        "# Generated by: preview-kit init",
        "",
        "[preview-kit]",
        f'project_name = "{cfg.project_name}"',
        f'project_prefix = "{cfg.project_prefix}"',
        f'host_pattern = "{cfg.host_pattern}"',
        f'compose_file = "{cfg.compose_file}"',
        f'health_path = "{cfg.health_path}"',
        f'base = "{cfg.base}"',
        f'shell_service = "{cfg.shell_service}"',
        f'test_service = "{cfg.test_service}"',
        f'test_command = "{cfg.test_command}"',
    ]

    if cfg.ports:
        lines.append("")
        lines.append("[preview-kit.ports]")
        for name, base in cfg.ports.items():
            lines.append(f"{name} = {base}")

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_justfile(repo_root: Path) -> bool:
    """Add 'import preview.just' to justfile if not present. Return True if added."""
    justfile_path = repo_root / "justfile"
    if not justfile_path.exists():
        raise InitError(f"justfile not found at {justfile_path}")

    content = justfile_path.read_text(encoding="utf-8")
    import_line = "import 'preview.just'"

    if import_line in content:
        return False  # Already present

    # Append import to end
    if not content.endswith("\n"):
        content += "\n"
    content += import_line + "\n"

    justfile_path.write_text(content, encoding="utf-8")
    return True


def init(
    repo_root: Path,
    preview_kit_path: Path,
    cfg: config.PreviewKitConfig,
    out: IO[str],
    force: bool = False,
) -> None:
    """Execute the full init flow."""
    out.write("\n=== preview-kit init ===\n\n")

    try:
        out.write("Creating symlink to preview.just...\n")
        symlink_preview_just(repo_root, preview_kit_path, force=force)

        out.write("Writing preview-kit.toml...\n")
        write_config(repo_root, cfg, force=force)

        out.write("Updating justfile...\n")
        added = update_justfile(repo_root)
        if added:
            out.write("  (added import 'preview.just')\n")
        else:
            out.write("  (import already present)\n")

        out.write("\n✓ Setup complete!\n\n")
        out.write("Next steps:\n\n")
        out.write(f"1. Create {cfg.compose_file} with your worktree stack.\n")
        out.write("   Include: services, COMPOSE_PROJECT_NAME override, ports, env vars.\n\n")
        out.write("2. Test the setup:\n")
        out.write("   preview-kit env     # verify env vars\n")
        out.write("   just worktree <slug>    # create test worktree\n")
        out.write("   just dev            # bring up the stack\n\n")
        out.write(f"3. Review preview-kit.toml in {repo_root}\n\n")

    except InitError as exc:
        raise InitError(f"Initialization failed: {exc}") from exc
